version: '2'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demo
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  redis:
    driver: local