version: '2'
services:
  db:
    image: mysql
    container_name: www-mysqldb
    environment:
      MYSQL_DATABASE: login
      MYSQL_USER: cockpit
      MYSQL_PASSWORD: x1ugOm71CraidpNs
      MYSQL_ROOT_PASSWORD: x1ugOm71CraidpNs
    volumes:
      - ./mysql/:/var/lib/mysql/
    restart: always
    ports:
      - 3306:3306
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  redis:
    driver: local